spring:
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mariadb://localhost:3306/divelink
    username: root
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # 개발 중에는 update, 배포 전에는 validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

  security:
    user:
      enabled: false  # 기본 사용자 인증 비활성화

  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 100MB

storage:
  type: s3   # local | s3  (운영에서는 s3)
  url-ttl-seconds: 1800
  local:
    base-path: ./uploads           # 실제 파일 저장 디렉터리
    public-base-url: http://localhost:8080/files  # 정적 서빙 URL prefix
  s3:
    bucket: divelink-uploads
    region: ap-northeast-2

#  jwt:
#    expiration_time: 86400000 #1일
#    secret:

server:
  port: 8080
  tomcat:
    max-http-form-post-size: 100MB   # 기본 2MB
    max-swallow-size: -1